Se realiza modificación del readme
AleksOrigen/practica-unir-cicd pull request #8
Opened 2024-10-04 19:00 UTC by jaimeandres1945

2024-10-06 09:45 UTC, joslopmol approved these changes

2024-10-07 21:38 UTC, AleksOrigen requested changes

2024-10-07 21:38 UTC, AleksOrigen commented on README.md
> +He modificado este readme para mostrar como se puede crear una nueva rama a partir de dev para resolver la issue
Added review to block the PR until resolved

2024-10-11 13:38 UTC, joslopmol approved these changes

2024-10-11 18:55 UTC, AleksOrigen approved these changes

2024-10-11 18:56 UTC, merged